# AI Model Configuration
type: ollama  # Options: openai, ollama, anthropic

# OpenAI Configuration
openai:
  api_key: ""  # Leave empty to use OPENAI_API_KEY environment variable
  model: "gpt-3.5-turbo"

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434"
  model: "qwen2.5:7b"

# Anthropic Configuration
anthropic:
  api_key: ""  # Leave empty to use ANTHROPIC_API_KEY environment variable
  model: "claude-3-opus-20240229" 